### ISSUE TITLE
Give full directory path to custom importers

### ISSUE THREAD

**Issue by sebakerckhof** [sass/node-sass#1188]
I'm writing a custom importer for node-sass.
The problem is that it seems node-sass runs through the imports breadth-first instead of depth-first.
That makes it hard to know which file is meant with only the 'prev' variable, as we cannot build a directory path.

Could the importer get either the full directory path instead of only the previous one, or could node-sass run through the imports depth-first (maybe with an option)?

**Comment by xzyfer** [comment]
This is fixed in the beta

```
npm  install node-sass@beta
```

**Comment by sebakerckhof** [comment]
This indeed seems to be the case, however I think I can still not guarantee to know the correct file, with only the previous path. I know it has backtracked when the previous directory I get in the importer != the directory of the last received url. However, if there are multiple parts in the path with the same name, then I have no idea how far it has backtracked (so in which file the new received url occurs).

**Comment by xzyfer** [comment]
Can you give me an example of how you want to use this? Not exposing the full path to the importers was a decision we made to prevent importers making code unportable.

**Comment by sebakerckhof** [comment]
I'll try to make an example repro that shows why having only the previous path can, in some (rare) cases, be insufficient to know which file is meant.

**Comment by xzyfer** [comment]
Sorry, I understand why prev alone does not give you the context to know
which file would have been imported.

I'm questioning why you would want to know in the context of a custom
importer? If you're providing a custom importer you're explicitly saying
yiu don't want the default behaviour.

**Comment by xzyfer** [comment]
Also, IIRC the arguments passed to the custom importer along with the load
path (include path) config is sufficient information to reimplement the
default behaviour.

**Comment by sebakerckhof** [comment]
Well, actually I want to build the default behavior with extensions.
In Meteor an application is split up in packages. Due to the way the packaging system works, it is hard to refer to a file in another package. Therefore they use file paths like: ' {packagename}/file/to/style.scss'. Inside of one package, import behavior should be the default behavior. So I'm trying to implement the default behavior extended with the cross-package references.

To implement the default behavior I keep a stack of previous paths I receive in the importer and concatenate them. 
If the previous path is not the same as the last received url, then we have backtracked in the sass import tree.
But I don't think I can always answer to which file libsass has backtracked, therefore I can not implement the default behavior. This is basically the same problem I have when the previous path is 'stdin', therefore I opened this issue: https://github.com/sass/node-sass/issues/1195

To make it more clear I just made an example importer that tries to mimick default behavior (although a bit simplified and with some assumptions). It shows that with only the include path and information passed to the importer, we can't always know the correct file (or at least I don't see how to do it):
https://github.com/sebakerckhof/node-sass-import2

**Comment by xzyfer** [comment]
I see. Now I understand. You want path alias like in requirejs or webpack i.e.

```
@import "package-x/foo/bar";
```

Where in you want node-sass to expand "package-x" to `/path/to/package-x/src/scss`. I have discussed having something like this in Ruby Sass but was convinced was a bad idea. The problem with this kind of "magic" importer is that is essentially locks code into an a specific importer to work.

Is two ways for you to implement your importer.

1) Assuming there is a predictable directory structure enforced by meteor you could simply do your own alias expanding. This can be done by inferring what directory `package-x` should expand too. If there are strong conventions in the meteor eco system this should be a piece of cake. If there are not, you could require the user to provide you with an object of aliases to paths. This can be done in an `.rc` file or their `package.json`.

2) Use symlinks (and the Windows equivalent). Require to user to symlink their package's assets folder into a single folder. Then add that folder to your load path i.e. 

```
symlink  `/path/to/package-x/src/scss -> my-app/assets/packages/package-x`
```
Now your import will work resolve correctly.
```
@import "package-x/foo/bar";
```

**Comment by sebakerckhof** [comment]
Yes, option one is what we're doing in our meteor build plugin ( https://github.com/fourseven/meteor-scss ). That it locks-in the user to our importer isn't much of a problem, since meteor packages are more or less locked into the framework anyway.

However, this alias expansion isn't the issue, the issue is that next to these package-urls, we also want to support relative urls, like the default node-sass behavior.

So you can have a file foo.scss in package foo:
```scss
@import "file/local/to/package.scss"
@import "{bar}/file/in/package/bar.scss"
```

And it's these relative urls that we need to know the whole path for. As shown here, the information of the include path and what is given to the importer does not suffice: https://github.com/sebakerckhof/node-sass-import2

**Comment by saper** [comment]
I think that neither libsass nor node-sass should assume the import identifiers and paths are real filesystem paths unless explicitly told so. Ruby implementation generally works like this except
for some little nasty bits for caching etc.

**Comment by xzyfer** [comment]
IMHO https://github.com/sass/node-sass/issues/1188#issuecomment-145493390 represents the best solution possible given the constraints of LibSass and the Sass language. I don't see what else can be done here.
