### ISSUE TITLE
Failed at the node-sass@3.6.0 postinstall script 'node scripts/build.js'  Exit status 1

### ISSUE THREAD

**Issue by trisquel87** [sass/node-sass#1581]
Hello, i have a problem when i try to do this:

`npm install -g node-sass@3.6.0`

My computer has this configuration: 

OS: Windows 7 64 bits
node v4.2.1
npm  v3.9.5

The error is:

> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass@3.6.0" "-g"
> npm ERR! node v4.2.1
> npm ERR! npm  v3.9.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@3.6.0 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@3.6.0 postinstall script 'node scripts/build.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/build.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-sass
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls node-sass
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\JRCI\npm-debug.log
> npm ERR! code 1
> 

I also try to install the node-sass 3.6.0 and 3.4.2 versions but i have the same problem.

**Comment by mimikn** [comment]
I also am unable to install node-sass@3.7.0, I'm stucked at the "node scripts/install.js".
Here are my infos : 
node@6.2.1
npm@3.9.6
darwin (OS X)
x64

**Comment by xzyfer** [comment]
Please provide the npm debug log file

**Comment by farhan687** [comment]
hi @xzyfer 
 Older version is working fine. but newer version has issue.

Log file portion:

587 verbose linkBins node-sass@3.7.0
588 verbose link bins [ { 'node-sass': 'bin/node-sass' },
588 verbose link bins   'D:\\Work\\xampp\\htdocs\\appbase-work\\es-queryComposer\\node_modules\\.bin',
588 verbose link bins   false ]
589 verbose linkMans node-sass@3.7.0
590 silly doSerial global-link 0
591 silly doParallel update-linked 0
592 silly doSerial install 1
593 silly install node-sass@3.7.0 D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\.staging\node-sass-5d87fd81
594 info lifecycle node-sass@3.7.0~install: node-sass@3.7.0
595 verbose lifecycle node-sass@3.7.0~install: unsafe-perm in lifecycle true
596 verbose lifecycle node-sass@3.7.0~install: PATH: C:\Users\farhan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\node-sass\node_modules\.bin;D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.6.0_21\bin;C:\Users\farhan\AppData\Roaming\npm;C:\Program Files\apache-ant-1.9.3\bin;C:\Users\farhan\AppData\Local\Android\android-sdk\tools;C:\Users\farhan\AppData\Local\Android\android-sdk\platform-tools;D:\Work\xampp;c:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\BrowseEmAll;C:\phantomjs\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\PostgreSQL\9.5\bin;C:\Program Files\PostgreSQL\9.5\lib;C:\Ruby22\bin;C:\Users\farhan\AppData\Local\atom\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby200-x64\bin;C:\Users\farhan\AppData\Roaming\npm\cordova.cmd;C:\Program Files\apache-ant-1.9.3;C:\Users\farhan\AppData\Local\.meteor\;C:\phantomjs\bin;C:\Program Files\PostgreSQL\9.5\bin;C:\Program Files\PostgreSQL\9.5\lib;C:\Ruby22\bin;C:\Users\farhan\AppData\Local\atom\bin;C:\Program Files\Docker Toolbox;C:\Users\farhan\AppData\Roaming\npm
597 verbose lifecycle node-sass@3.7.0~install: CWD: D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\node-sass
598 silly lifecycle node-sass@3.7.0~install: Args: [ '/d /s /c', 'node scripts/install.js' ]
599 silly lifecycle node-sass@3.7.0~install: Returned: code: 0  signal: null
600 silly doSerial postinstall 1
601 silly postinstall node-sass@3.7.0 D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\.staging\node-sass-5d87fd81
602 info lifecycle node-sass@3.7.0~postinstall: node-sass@3.7.0
603 verbose lifecycle node-sass@3.7.0~postinstall: unsafe-perm in lifecycle true
604 verbose lifecycle node-sass@3.7.0~postinstall: PATH: C:\Users\farhan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\node-sass\node_modules\.bin;D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.6.0_21\bin;C:\Users\farhan\AppData\Roaming\npm;C:\Program Files\apache-ant-1.9.3\bin;C:\Users\farhan\AppData\Local\Android\android-sdk\tools;C:\Users\farhan\AppData\Local\Android\android-sdk\platform-tools;D:\Work\xampp;c:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\BrowseEmAll;C:\phantomjs\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\PostgreSQL\9.5\bin;C:\Program Files\PostgreSQL\9.5\lib;C:\Ruby22\bin;C:\Users\farhan\AppData\Local\atom\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby200-x64\bin;C:\Users\farhan\AppData\Roaming\npm\cordova.cmd;C:\Program Files\apache-ant-1.9.3;C:\Users\farhan\AppData\Local\.meteor\;C:\phantomjs\bin;C:\Program Files\PostgreSQL\9.5\bin;C:\Program Files\PostgreSQL\9.5\lib;C:\Ruby22\bin;C:\Users\farhan\AppData\Local\atom\bin;C:\Program Files\Docker Toolbox;C:\Users\farhan\AppData\Roaming\npm
605 verbose lifecycle node-sass@3.7.0~postinstall: CWD: D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\node-sass
606 silly lifecycle node-sass@3.7.0~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
607 silly lifecycle node-sass@3.7.0~postinstall: Returned: code: 1  signal: null
608 info lifecycle node-sass@3.7.0~postinstall: Failed to exec postinstall script
609 verbose unlock done using C:\Users\farhan\AppData\Roaming\npm-cache\_locks\staging-76cf6e158c445fc6.lock for D:\Work\xampp\htdocs\appbase-work\es-queryComposer\node_modules\.staging
610 silly rollbackFailedOptional Starting
611 silly rollbackFailedOptional Finishing
612 silly runTopLevelLifecycles Starting
613 silly runTopLevelLifecycles Finishing
614 silly install printInstalled
615 warn optional Skipping failed optional dependency /chokidar/fsevents:
616 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
617 warn optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
618 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
619 warn es-query-composer@1.0.0 No repository field.
620 verbose stack Error: node-sass@3.7.0 postinstall: `node scripts/build.js`
620 verbose stack Exit status 1
620 verbose stack     at EventEmitter.<anonymous> (C:\Users\farhan\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
620 verbose stack     at emitTwo (events.js:100:13)
620 verbose stack     at EventEmitter.emit (events.js:185:7)
620 verbose stack     at ChildProcess.<anonymous> (C:\Users\farhan\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
620 verbose stack     at emitTwo (events.js:100:13)
620 verbose stack     at ChildProcess.emit (events.js:185:7)
620 verbose stack     at maybeClose (internal/child_process.js:850:16)
620 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
621 verbose pkgid node-sass@3.7.0
622 verbose cwd D:\Work\xampp\htdocs\appbase-work\es-queryComposer
623 error Windows_NT 6.3.9600
624 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\farhan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
625 error node v5.10.1
626 error npm  v3.9.5
627 error code ELIFECYCLE
628 error node-sass@3.7.0 postinstall: `node scripts/build.js`
628 error Exit status 1
629 error Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
629 error Make sure you have the latest version of node.js and npm installed.
629 error If you do, this is most likely a problem with the node-sass package,
629 error not with npm itself.
629 error Tell the author that this fails on your system:
629 error     node scripts/build.js
629 error You can get information on how to open an issue for this project with:
629 error     npm bugs node-sass
629 error Or if that isn't available, you can get their info via:
629 error     npm owner ls node-sass
629 error There is likely additional logging output above.
630 verbose exit [ 1, true ]

**Comment by xzyfer** [comment]
Unfortunately your logs do not provide any useful information. Can you please confirm what OS you're running, and which "old version" of node-sass works?

**Comment by saper** [comment]
@trisquel87  is node on your PATH?

**Comment by tmwheel** [comment]
I'm having the same problem with 3.8:
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.

Yes, node is on my path.

**Comment by Sobak** [comment]
As related to installing issue with 3.8.0, I think I have more detailed error message:

```shell
35962 verbose stack Error: node-sass@3.8.0 postinstall: `node scripts/build.js`
35962 verbose stack Exit status 1
35962 verbose stack     at EventEmitter.<anonymous> (C:\WWW\nodejs\node_modules\npm\lib\utils\lifecycle.js:244:16)
35962 verbose stack     at emitTwo (events.js:87:13)
35962 verbose stack     at EventEmitter.emit (events.js:172:7)
35962 verbose stack     at ChildProcess.<anonymous> (C:\WWW\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
35962 verbose stack     at emitTwo (events.js:87:13)
35962 verbose stack     at ChildProcess.emit (events.js:172:7)
35962 verbose stack     at maybeClose (internal/child_process.js:827:16)
35962 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
35963 verbose pkgid node-sass@3.8.0
35964 verbose cwd D:\WWW\htdocs\codice
35965 error Windows_NT 10.0.10586
35966 error argv "C:\\WWW\\nodejs\\node.exe" "C:\\WWW\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
35967 error node v4.4.3
35968 error npm  v3.8.8
35969 error code ELIFECYCLE
35970 error node-sass@3.8.0 postinstall: `node scripts/build.js`
```

**Comment by Alexorz** [comment]
Maybe a same issue here with node@6.1.0 & node-sass@3.8.0 on Ubuntu and Mac.

````
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/root/.nvm/versions/node/v6.1.0/bin/node" "/root/.nvm/versions/node/v6.1.0/bin/npm" "i"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/plover/npm-debug.log
````

npm-debug.log
````
155769 info lifecycle lodash.assign@4.0.9~postinstall: lodash.assign@4.0.9
155770 silly lifecycle lodash.assign@4.0.9~postinstall: no script for postinstall, continuing
155771 silly postinstall yargs-parser@2.4.0 /var/app/plover/node_modules/.staging/yargs-parser-32b5586d
155772 info lifecycle yargs-parser@2.4.0~postinstall: yargs-parser@2.4.0
155773 silly lifecycle yargs-parser@2.4.0~postinstall: no script for postinstall, continuing
155774 silly postinstall yargs@4.7.1 /var/app/plover/node_modules/.staging/yargs-f3907e84
155775 info lifecycle yargs@4.7.1~postinstall: yargs@4.7.1
155776 silly lifecycle yargs@4.7.1~postinstall: no script for postinstall, continuing
155777 silly postinstall sass-graph@2.1.2 /var/app/plover/node_modules/.staging/sass-graph-8b66ed02
155778 info lifecycle sass-graph@2.1.2~postinstall: sass-graph@2.1.2
155779 silly lifecycle sass-graph@2.1.2~postinstall: no script for postinstall, continuing
155780 silly postinstall node-sass@3.8.0 /var/app/plover/node_modules/.staging/node-sass-3b0a8fff
155781 info lifecycle node-sass@3.8.0~postinstall: node-sass@3.8.0
155782 verbose lifecycle node-sass@3.8.0~postinstall: unsafe-perm in lifecycle false
155783 verbose lifecycle node-sass@3.8.0~postinstall: PATH: /root/.nvm/versions/node/v6.1.0/lib/node_modules/npm/bin/node-gyp-bin:/var/app/plover/node_modules/node-sass/node_modules/.bin:/var/app/plover/n
ode_modules/.bin:/root/.nvm/versions/node/v6.1.0/bin:/root/.nvm/versions/node/v6.1.0/bin:/usr/lib/jvm/jdk1.8.0_77/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
es
155784 verbose lifecycle node-sass@3.8.0~postinstall: CWD: /var/app/plover/node_modules/node-sass
155785 silly lifecycle node-sass@3.8.0~postinstall: Args: [ '-c', 'node scripts/build.js' ]
155786 silly lifecycle node-sass@3.8.0~postinstall: Returned: code: 1  signal: null
155787 info lifecycle node-sass@3.8.0~postinstall: Failed to exec postinstall script
155788 verbose unlock done using /root/.npm/_locks/staging-c074e8948ca27c12.lock for /var/app/plover/node_modules/.staging
155789 silly rollbackFailedOptional Starting
155790 silly rollbackFailedOptional Finishing
155791 silly runTopLevelLifecycles Starting
155792 silly runTopLevelLifecycles Finishing
155793 silly install printInstalled
155794 warn optional Skipping failed optional dependency /chokidar/fsevents:
155795 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
155796 warn browserify-shim@2.0.10 requires a peer of browserify@>= 2.3.0 < 4 but none was installed.
155797 verbose stack Error: node-sass@3.8.0 postinstall: `node scripts/build.js`
155797 verbose stack Exit status 1
155797 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
155797 verbose stack     at emitTwo (events.js:106:13)
155797 verbose stack     at EventEmitter.emit (events.js:191:7)
155797 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
155797 verbose stack     at emitTwo (events.js:106:13)
155797 verbose stack     at ChildProcess.emit (events.js:191:7)
155797 verbose stack     at maybeClose (internal/child_process.js:850:16)
155797 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
155798 verbose pkgid node-sass@3.8.0
155799 verbose cwd /var/app/plover
155800 error Linux 3.13.0-32-generic
155801 error argv "/root/.nvm/versions/node/v6.1.0/bin/node" "/root/.nvm/versions/node/v6.1.0/bin/npm" "i"
155802 error node v6.1.0
155803 error npm  v3.8.6
155804 error code ELIFECYCLE
155805 error node-sass@3.8.0 postinstall: `node scripts/build.js`
155805 error Exit status 1
155806 error Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
155806 error Make sure you have the latest version of node.js and npm installed.
155806 error If you do, this is most likely a problem with the node-sass package,
155806 error not with npm itself.
155806 error Tell the author that this fails on your system:
155806 error     node scripts/build.js
155806 error You can get information on how to open an issue for this project with:
155806 error     npm bugs node-sass
155806 error Or if that isn't available, you can get their info via:
155806 error     npm owner ls node-sass
155806 error There is likely additional logging output above.
155807 verbose exit [ 1, true ]
````

**Comment by xzyfer** [comment]
These look like permission issues. Make sure you have permission execute in
your install directory. You can confirm a permission issue with `npm
install --unsafe-perm`

**Comment by skhamoud** [comment]
Still waiting on a Solution for this installation error of node-sass@3.8.0 postinstall

**Comment by mattythebatty** [comment]
I was having this issue in an alpine docker image. I eventually found that I needed g++ available so that node-sass could run the build script. (I already had nodejs, python & make)

**Comment by aslani75** [comment]
Same issue here to, anyone solved this?

my setup:
Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 7 SP1
Node Version: v6.3.1


the error log:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm verb stack Error: node-sass@3.8.0 postinstall: `node scripts/build.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\aberec\AppData\Roaming\
npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\aberec\AppData\Roaming\
npm\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:5)
npm verb pkgid node-sass@3.8.0
npm verb cwd C:\Users\aberec\ionic_projects\VERSION2\ionic-conference-app-typesc
ript
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aberec\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-verbose"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\aberec\ionic_projects\VERSION2\ionic-conference-app-typesc
ript\npm-debug.log

**Comment by saper** [comment]
@aslani75 can you check earlier in the log (unfortunately the console is the best) why scripts/install.js failed? This one should download the required binary for you automatically.

**Comment by faradoxuz** [comment]
same issue

**Comment by faradoxuz** [comment]
`sudo ln -s /usr/bin/nodejs /usr/bin/node` this helped for me

**Comment by dongalor** [comment]
same issue, please help, trying to build on osx yosemite

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> node-sass@0.9.6 install /Users/zul/Code/ruby/fh-admin/node_modules/node-sass
> node build.js

(node:22363) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:1:
../../nan/nan.h:189:68: error: too many arguments to function call, expected at most 2, have 4
    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/zul/.node-gyp/6.4.0/include/node/v8.h:4798:3: note: 'New' declared here
  static Local<Signature> New(
  ^
In file included from ../binding.cpp:1:
../../nan/nan.h:271:3: error: redefinition of 'NanNew'
  NanNew<v8::StringObject, v8::Handle<v8::String> >(
  ^
../../nan/nan.h:264:3: note: previous definition is here
  NanNew<v8::StringObject, v8::Local<v8::String> >(
  ^
../../nan/nan.h:289:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:283:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:301:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:295:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:481:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/zul/.node-gyp/6.4.0/include/node/v8.h:2230:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../binding.cpp:1:
../../nan/nan.h:480:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../../nan/nan.h:475:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../../nan/nan.h:495:27: error: redefinition of '_NanEscapeScopeHelper'
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:490:27: note: previous definition is here
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
                          ^
../../nan/nan.h:511:12: error: no matching function for call to '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Primitive]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:516:12: error: no matching function for call to '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Primitive]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:521:12: error: no matching function for call to '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Boolean]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:526:12: error: no matching function for call to '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Boolean]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:567:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:573:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:578:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:584:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:755:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:766:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/zul/.node-gyp/6.4.0/include/node/node_buffer.h:46:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/zul/.node-gyp/6.4.0/include/node/node_buffer.h:34:40: note: candidate function not viable: no known conversion from 'const char *' to 'v8::Local<v8::String>' for 2nd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/zul/.node-gyp/6.4.0/include/node/node_buffer.h:31:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/zul/.node-gyp/6.4.0/include/node/node_buffer.h:39:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../binding.cpp:1:
../../nan/nan.h:770:12: error: no viable conversion from returned value of type 'v8::MaybeLocal<v8::Object>' to function return type 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/zul/.node-gyp/6.4.0/include/node/v8.h:216:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/zul/.node-gyp/6.4.0/include/node/v8.h:216:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object> &&' for 1st argument
/Users/zul/.node-gyp/6.4.0/include/node/v8.h:220:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:777:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zul/Code/ruby/fh-admin/node_modules/node-sass
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
npm WARN gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
npm WARN karma-jasmine@0.1.6 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-phantomjs-launcher@0.1.4 requires a peer of karma@>=0.9 but none was installed.
npm WARN fhAdmin@0.0.0 No description
npm WARN fhAdmin@0.0.0 No repository field.
npm WARN fhAdmin@0.0.0 No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zul/Code/ruby/fh-admin/npm-debug.log

**Comment by saper** [comment]
@dongalor your ancient node-sass@0.9.6 will not work with the recent node engines. Please update node-sass to the latest version.

**Comment by Pizdetss** [comment]
Still an issue.

**Comment by saper** [comment]
@Pizdetss what a nickname, man

**Comment by rishantagarwal** [comment]
Updating the package works. Thanks :+1:

**Comment by hxshandle** [comment]
Hi Same issue with me. Anyone can help?
I'm use Ubuntu 14.04 64bit

6336 silly runTopLevelLifecycles Starting
6337 silly runTopLevelLifecycles Finishing
6338 silly install printInstalled
6339 warn optional Skipping failed optional dependency /chokidar/fsevents:
6340 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
6341 verbose stack Error: node-sass@3.9.3 postinstall: `node scripts/build.js`
6341 verbose stack Exit status 135
6341 verbose stack     at EventEmitter.<anonymous> (/home/iogym/nodejs.4.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
6341 verbose stack     at emitTwo (events.js:87:13)
6341 verbose stack     at EventEmitter.emit (events.js:172:7)
6341 verbose stack     at ChildProcess.<anonymous> (/home/iogym/nodejs.4.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
6341 verbose stack     at emitTwo (events.js:87:13)
6341 verbose stack     at ChildProcess.emit (events.js:172:7)
6341 verbose stack     at maybeClose (internal/child_process.js:829:16)
6341 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
6342 verbose pkgid node-sass@3.9.3
6343 verbose cwd /home/iogym/git.osc/gym
6344 error Linux 3.13.0-86-generic
6345 error argv "/usr/bin/nodejs" "/home/iogym/nodejs.4.5/bin/npm" "i"
6346 error node v4.5.0
6347 error npm  v3.10.6
6348 error code ELIFECYCLE
6349 error node-sass@3.9.3 postinstall: `node scripts/build.js`
6349 error Exit status 135

**Comment by saper** [comment]
> 
> 6348 error code ELIFECYCLE
> 6349 error node-sass@3.9.3 postinstall: `node scripts/build.js`
> 6349 error Exit status 135

Can you follow TROUBLESHOOTING.md?

I guess your "node" and "nodejs" are two different beasts.

**Comment by nschonni** [comment]
Closing since there are various unrelated issues in this tread

**Comment by Nirmal12** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN tradespeople@1.0.0 No license field.
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/nirmalsekar/.asdf/installs/nodejs/6.8.1/bin/node" "/home/nirmalsekar/.asdf/installs/nodejs/6.8.1/.npm/bin/npm" "install"
npm ERR! node v6.8.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nirmalsekar/Projects/tradespeople-web/npm-debug.log

**Comment by jackytedy** [comment]
It help me. :+1:

**Comment by coradinibr** [comment]
npm rebuild node-sass

**Comment by EugeValeiras** [comment]
Sometimes works and sometimes doesn't (IN HEROKU)

**package.json**
"scripts": {
"preinstall": "npm rebuild node-sass && npm i typings@2.1.0 -g && npm install -g typescript@2.2.2 && typings install && tsc -p tsconfig.json",
    "postinstall": "ng build",
}
```

**Comment by cmdelatorre** [comment]
Something similar happened to us. Given [this comment](https://github.com/sass/node-sass/issues/1962#issuecomment-298876189) I think it may be related to internet issues during the install.

**Comment by Jrexexe** [comment]
Same issue here to

2426 verbose stack Error: node-sass@4.9.2 postinstall: `node scripts/build.js`
2426 verbose stack Exit status 1
2426 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
2426 verbose stack     at emitTwo (events.js:126:13)
2426 verbose stack     at EventEmitter.emit (events.js:214:7)
2426 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2426 verbose stack     at emitTwo (events.js:126:13)
2426 verbose stack     at ChildProcess.emit (events.js:214:7)
2426 verbose stack     at maybeClose (internal/child_process.js:925:16)
2426 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by saper** [comment]
@Jrexexe can you go through the steps described in TROUBLESHOOTING.md file?

**Comment by marlonwilliams** [comment]
upgrade to the latest Node.js (v10+) and this should resolve the issue

**Comment by NickyWisenov** [comment]
I have tried using node 10.4.1 but it also doesn't work, same error caused. Need professional help

**Comment by Stefanbracke** [comment]
This still doesn't work. Come one, this has been floating around for 2 years.

**Comment by saper** [comment]
@Stefanbracke this looks like a potpourri of some issues related to node installation. We can't even put additional logging before our script even starts.

**Comment by radicalsamurai** [comment]
I ran into this issue as well when trying to install node-sass.  I removed the command sudo (as I'm on mac), and ran it again, and it work for some reason without throwing those same errors.

**Comment by bansalp004** [comment]
did npm install node-sass  -- all worked after that.
