### ISSUE TITLE
Segfault with function/map combination

### ISSUE THREAD

**Issue by danez** [sass/node-sass#1861]
- NPM version (`npm -v`): 4.1.1
- Node version (`node -v`): 6.9.3
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '6.9.3',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.3.0	(Wrapper)	[JavaScript]
libsass  	3.4.3	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
root@ /hdir
└── node-sass@4.3.0 
```

<hr/>

We receive random segfaults when running `grunt-sass` on our large codebase. I used `segfault-handler` to catch the error and print something useful and this is all I got:

```
PID 19883 received SIGSEGV for address: 0x26a36c0
/hdir/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1b53)[0x7f3f104b2b53]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7f3f12a8e330]
[0x26a36c0]
```

I also tried compiling a debug version of the node-sass binding, but that didn't change the segfault output.

I tried changing grunt-sass to use `sass.renderSync()` and not do any async stuff, but besides being slower the same error appears again.

Our codebase works with 3.x

**Comment by danez** [comment]
I found a small reproducable case: It seems this problem is not relevant to grunt-sass

```scss
@function map-include($map, $keys...) {
  $map-include: ();
  @each $key in $keys {
    @if map-has-key($map, $key) {
      $map-include: map-merge($map-include, ($key: map-get($map, $key)));
    } @else {
      @error 'Oooops! #{$key} is not included in map #{$map}';
    }
  }
  @return $map-include;
}


$colors: (
        "white": #FFFFFF,
        "black": #000000,
        "green-50": #F0F7F7
);

$list-colors: map-include($colors, 'white', 'black') !default;
```

**Comment by xzyfer** [comment]
Thanks for the reproduction @danez. This has been fixed in LibSass 3.5.0.beta.2 and will be released in node-sas@v4.4.0 in the next couple days.

**Comment by xzyfer** [comment]
@danez can you confirm the segfault is resolved with `node-sass@beta`?

**Comment by danez** [comment]
Sadly it still does not work, I open another ticket, as different problem.

**Comment by patrickording** [comment]
I ran into the same issue using [scss maps](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps) having the following environment:

![bildschirmfoto 2017-02-01 um 14 17 34](https://cloud.githubusercontent.com/assets/6302299/22508219/50e822b8-e889-11e6-9edc-1d5639e2d4a4.png)
