### ISSUE TITLE
Node 9 support (module 59)

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#2129]
Preemptivly opening this issue since Node 9 was released today. We'll use this issue to track adding the support and close other issues.
- [x] Update Travis #2130
- [x] Update Appveyor #2130, but blocked by https://github.com/appveyor/ci/issues/1895
- [x] Allow module 59 as a valid version #2130
- [x] Build OSX
- [x] Build Windows
- [x] Build Linux
- [x] Build Alpine
- [ ] Build FreeBSD

## Install version 4.6.0+ for Node 9 support

**Comment by xnnkmd** [comment]
Will this address the following problem where python seem to be required to install  under node 9 ?:

```
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Source\\Repos\\Gandalf\\src\\Gandalf.Web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
```
g

**Comment by revelt** [comment]
It does not work on 9. I get error messages. Pls fix.

**Comment by mtpaluszkiewicz** [comment]
```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/office-ui-fabric-react/dist/sass/Fabric.scss
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (59)
```

**Comment by graingert** [comment]
@xnnkmd that just sounds like you've not python2 installed.

**Comment by depsypher** [comment]
Started getting build failures for our app last night (using node 9):
```
+ npm install

> node-sass@4.5.2 install /home/circleci/houston/src/main/frontend/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-59_binding.node": 
```

Not sure why it's looking for ```linux-x64-59_binding.node``` when ```linux-x64-57_binding.node``` seems to be the latest release.

Is this a node-sass issue?

**Comment by SomethingNew71** [comment]
@depsypher I think the answer to your question is in the title of this issue

> Node 9 support (module 59)

**Comment by Burhan1991** [comment]
@depsypher same here.

Also tried renaming latest win32-x64-**57**_binding.node to win32-x64-**59**_binding.node and put it in the dependent node_module.
Got this message:

```
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
```

Only now just by the error message I did understand that Node.js 9 is not support yet.

**Comment by xzyfer** [comment]
Wait until this issue is closed. There is no need to comment any further.

**Comment by stefanpenner** [comment]
is this fixed by: https://github.com/sass/node-sass/pull/2130 ?

**Comment by xzyfer** [comment]
Yes.

**Comment by nschonni** [comment]
4.6.0 has been released with support for node 9 https://github.com/sass/node-sass/releases/tag/v4.6.0
There are bindings for Alpine and FreeBSD still missing, but they will just be attached to the release

**Comment by mrgrotts** [comment]
I can't get the updated version via NPM - can you update us when it's available?

**Comment by nschonni** [comment]
@LaurentGoderre or @saper looks like you have the ability to cut an NPM release. The git tag is done, just need the NPM part now.

**Comment by xzyfer** [comment]
I haven't published 4.6.0 yet. Didn't want to publish it the go to sleep.
Will publish it shortly.

**Comment by xzyfer** [comment]
4.6.0 has now been published.

**Comment by LaurentGoderre** [comment]
How do you get Alpine working? I'm really curious

**Comment by nschonni** [comment]
@LaurentGoderre info is over in #1996 in the linked repo. Should add some compose files though, but I never finished them up

**Comment by LaurentGoderre** [comment]
Aah so it's sort of a sneaky way! a good one though

**Comment by saper** [comment]
Strange, I encounter this error when trying to `npm install --ignore-scripts` on FreeBSD node 9.x:

````
/usr/local/bin/node[8979]: ../src/node_zlib.cc:430:static void node::<anonymous namespace>::ZCtx::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
*** Signal 6
````
Looks quite similar to https://github.com/nodejs/node/issues/13082

**Comment by smakosh** [comment]
I'm still having this issue

**Comment by xzyfer** [comment]
npm install node-sass@^4.7.2

**Comment by smakosh** [comment]
yarn add doesn't seem to work but npm install did work! Thanks

**Comment by VishalGrover** [comment]
node-sass@4.7.2 worked for me.

**Comment by nschonni** [comment]
Locking this as the only outstanding issue is FreeBSD binaries.

**Comment by saper** [comment]
Yep, uploaded for 4.7.2
