### ISSUE TITLE
cannot install node-sass@4.9.3

### ISSUE THREAD

**Issue by IvannaBabchanik** [sass/node-sass#2547]
node version v11.2.0

Steps:
npm i node-sass@4.9.3
Observed: 
 node-sass@4.9.3 install C:\Users\Ivanna_Babchanik\Documents\web-drillplan\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node":

HTTP error 404 Not Found

Expected:  should be installed without any issues
NOTE: node-sass@4.10.0 installed without any issue.

**Comment by xzyfer** [comment]
Sounds like the problem is fixed.

**Comment by IvannaBabchanik** [comment]
The problem is still observed, because I need 4.9.3 version not 4.10.0

**Comment by xzyfer** [comment]
We can't backport support for old new versions of Node. If you need 4.9 the you'll need to use Node < 10

**Comment by Lonzak** [comment]
Also have that problem, so it is not fixed...

**Comment by nschonni** [comment]
No, nothing was removed, it was never a supported combination

**Comment by tedHagler** [comment]
I'm trying to get my computer all setup to use SPFx and am having the same problem. I've installed the latest version of node-sass (v6.12.1) & refreshed it. But I still get the same error as above. Is there a way to change the reference to point to the latest build? Seems silly they would point a reference to a version that doesn't exist.

`Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node":

HTTP error 404 Not Found`

**Comment by saper** [comment]
@tedHagler There is no node-sass version 6.12.1 as of yet. You might have mean "npm". The error messages indicate you are trying to use Node 12 while v4.9.3 supports at most Node 10.
Look for node-sass in your dependencies `package.json` files and find one which hardcodes it to 4.9.3.

**Comment by MaxySpark** [comment]
where is https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node ?
