### ISSUE TITLE
tunneling socket could not be established, cause=Parse Error

### ISSUE THREAD

**Issue by gajus** [sass/node-sass#588]
```
npm info install node-sass@2.0.0-beta

> node-sass@2.0.0-beta install /app/app/2014 12 27 carcass/node_modules/node-sass
> node scripts/install.js

tunneling socket could not be established, cause=Parse Error
tunneling socket could not be established, cause=Parse Error
fs.js:75
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, unlink '/app/app/2014 12 27 carcass/node_modules/node-sass/vendor/linux-x64/binding.node'
    at Error (native)

npm info node-sass@2.0.0-beta Failed to exec install script
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/node/node-v0.11.14/bin/node" "/usr/local/node/node-default/bin/npm" "install" "node-sass"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-sass@2.0.0-beta install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@2.0.0-beta install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm info preuninstall node-sass@2.0.0-beta
npm info uninstall node-sass@2.0.0-beta
npm info postuninstall node-sass@2.0.0-beta
```

**Comment by am11** [comment]
Hello,

This seems like misconfigured npm.
Does [this](http://stackoverflow.com/q/17324438/863980) help? I would start with the one which says set registry and then proxy.

**Comment by gajus** [comment]
* I am not using a proxy.
* My registry is set to the default
* I have updated to the latest version of NPM

```sh
npm info install node-sass@1.2.3

> node-sass@1.2.3 install /app/app/2014 12 27 carcass/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

tunneling socket could not be established, cause=Parse Error
tunneling socket could not be established, cause=Parse Error
fs.js:75
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, unlink '/app/app/2014 12 27 carcass/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node'
    at Error (native)
npm info node-sass@1.2.3 Failed to exec install script
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "node" "/usr/local/node/node-default/bin/npm" "install" "gulp-sass" "--save-dev"
npm ERR! node v0.11.14
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm info preuninstall node-sass@1.2.3
npm info uninstall node-sass@1.2.3
npm info postuninstall node-sass@1.2.3
npm info preuninstall gulp-sass@1.2.4
npm info uninstall gulp-sass@1.2.4
npm info postuninstall gulp-sass@1.2.4

npm ERR! Please include the following file with any support request:
npm ERR!     /app/app/2014 12 27 carcass/npm-debug.log
```

**Comment by am11** [comment]
Do you get the same result, if you try the following:

```bash
mkdir /temp; cd /temp
npm install node-sass
# it should install node-sass latest version: v2.0.0-beta
```

**Comment by gajus** [comment]
I did that and I get the exact same result:

```
npm info linkStuff node-sass@2.0.0-beta
npm info install node-sass@2.0.0-beta

> node-sass@2.0.0-beta install /test/node_modules/node-sass
> node scripts/install.js

tunneling socket could not be established, cause=Parse Error
tunneling socket could not be established, cause=Parse Error
fs: missing callback Error: ENOENT, unlink '/test/node_modules/node-sass/vendor/linux-x64/binding.node'
npm info postinstall node-sass@2.0.0-beta

> node-sass@2.0.0-beta postinstall /test/node_modules/node-sass
> node scripts/build.js

node-sass@2.0.0-beta node_modules/node-sass
├── object-assign@2.0.0
├── get-stdin@3.0.2
├── replace-ext@0.0.1
├── shelljs@0.3.0
├── nan@1.4.1
├── mkdirp@0.5.0 (minimist@0.0.8)
├── cross-spawn@0.2.3 (lru-cache@2.5.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── meow@2.0.0 (object-assign@1.0.0, minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.0)
├── gaze@0.5.1 (globule@0.1.0)
├── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, jade@0.26.3, debug@2.0.0, glob@3.2.3)
└── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, tough-cookie@0.12.1, hawk@1.1.1, form-data@0.2.0, http-signature@0.10.0, bl@0.9.3)
npm info ok
[root@localhost test]#
```

**Comment by am11** [comment]
@kevva, any ideas what's going wrong?

I tried and succeeded. Here is the log:

```bash
vagrant@precise64:/temp/test-install$ uname -r
3.11.0-15-generic

vagrant@precise64:/temp/test-install$ cat /etc/issue
Ubuntu 12.04.5 LTS \n \l

vagrant@precise64:/temp/test-install$ node -p process.versions
{ http_parser: '1.0',
  node: '0.10.32',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.28',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1i' }

vagrant@precise64:/temp/test-install$ npm install node-sass
|
> node-sass@2.0.0-beta install /temp/test-install/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /temp/test-install/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@2.0.0-beta postinstall /temp/test-install/node_modules/node-sass
> node scripts/build.js

node-sass@2.0.0-beta node_modules/node-sass
├── get-stdin@3.0.2
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── shelljs@0.3.0
├── cross-spawn@0.2.3 (lru-cache@2.5.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── nan@1.4.1
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── meow@2.0.0 (object-assign@1.0.0, minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.0)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4,
 oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, bl@0.9.3, tou
gh-cookie@0.12.1, form-data@0.2.0, hawk@1.1.1, http-signature@0.10.0)
└── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, glob@3.2.3, jade@0.2
6.3)

vagrant@precise64:/temp/test-install$ node node_modules/.bin/node-sass --help

  Wrapper around libsass

  node-sass version: 2.0.0-beta
  libsass version: 3.1.0-beta

  Usage
    node-sass [options] <input.scss> [output.css]
    cat <input.scss> | node-sass > output.css

  Example
    node-sass --output-style compressed foobar.scss foobar.css
    cat foobar.scss | node-sass --output-style compressed > foobar.css

  Options
    -w, --watch                Watch a directory or file
    -r, --recursive            Recursively watch directories or files
    -o, --output               Output directory
    -x, --omit-source-map-url  Omit source map URL comment from output
    -i, --indented-syntax      Treat data from stdin as sass code (versus scss)
    --output-style             CSS output style (nested|expanded|compact|compressed)
    --source-comments          Include debug info in output
    --source-map               Emit source map
    --source-map-embed         Embed sourceMappingUrl as data URI
    --source-map-contents      Embed include contents in map
    --include-path             Path to look for imported files
    --image-path               Path to prepend when using the `image-url()` helper
    --precision                The amount of precision allowed in decimal numbers
    --stdout                   Print the resulting CSS to stdout
    --importer                 Path to custom importer
    --help                     Print usage info

vagrant@precise64:/temp/test-install$
```

**Comment by gajus** [comment]
Just to be clear, I am doing this on CentOS:

```
[vagrant@localhost test]$ cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m
```

**Comment by xzyfer** [comment]
I've just into this myself. The issue is on this line https://github.com/sass/node-sass/blob/master/scripts/install.js#L50.

`npm config get xx` sometimes returns `npm info it worked if it ends with ok` with `proxy.code === 0`. This results in `result` being set to `npm info it worked if it ends with ok`.

**Comment by am11** [comment]
Thanks a bunch @xzyfer! I have pushed the fix based on your commit. :+1:

**Comment by aschmid** [comment]
i am still experiencing the same issue on openshift...
  
    remote: make: Entering directory '/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxxx/app-root/runtime/repo/node_modules/node-sass/build'
    remote:   CXX(target) Release/obj.target/binding/src/binding.o
    remote: In file included from ../src/binding.cpp:3:
    remote: ../src/sass_context_wrapper.h:2:34: error: libsass/sass_context.h: No such file or directory
    remote: In file included from ../src/binding.cpp:3:
    remote: ../src/sass_context_wrapper.h:26: error: ISO C++ forbids declaration of 'Sass_Import' with no type
    remote: ../src/sass_context_wrapper.h:26: error: expected ';' before '*' token
    remote: ../src/binding.cpp: In function 'void prepare_import_results(v8::Local<v8::Value>, sass_context_wrapper*)':
    remote: ../src/binding.cpp:24: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp:24: error: 'sass_make_import_list' was not declared in this scope
    remote: ../src/binding.cpp:36: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp:36: error: 'sass_make_import_entry' was not declared in this scope
    remote: ../src/binding.cpp:40: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp:40: error: 'sass_make_import_list' was not declared in this scope
    remote: ../src/binding.cpp:45: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp:45: error: 'sass_make_import_entry' was not declared in this scope
    remote: ../src/binding.cpp:48: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp:48: error: 'sass_make_import_list' was not declared in this scope
    remote: ../src/binding.cpp:49: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp:49: error: 'sass_make_import_entry' was not declared in this scope
    remote: ../src/binding.cpp: In function 'Sass_Import** sass_importer(const char*, const char*, void*)':
    remote: ../src/binding.cpp:104: error: 'struct sass_context_wrapper' has no member named 'imports'
    remote: ../src/binding.cpp: In function 'void ExtractOptions(v8::Local<v8::Object>, void*, sass_context_wrapper*, bool, bool)':
    remote: ../src/binding.cpp:116: error: 'sass_file_context_get_context' was not declared in this scope
    remote: ../src/binding.cpp:120: error: 'sass_data_context_get_context' was not declared in this scope
    remote: ../src/binding.cpp:123: error: 'sass_context_get_options' was not declared in this scope
    remote: ../src/binding.cpp:144: error: 'sass_make_importer' was not declared in this scope
    remote: ../src/binding.cpp:144: error: 'sass_option_set_importer' was not declared in this scope
    remote: ../src/binding.cpp:148: error: 'sass_option_set_input_path' was not declared in this scope
    remote: ../src/binding.cpp:151: error: 'sass_option_set_output_path' was not declared in this scope
    remote: ../src/binding.cpp:152: error: 'sass_option_set_image_path' was not declared in this scope
    remote: ../src/binding.cpp:153: error: 'Sass_Output_Style' was not declared in this scope
    remote: ../src/binding.cpp:153: error: 'sass_option_set_output_style' was not declared in this scope
    remote: ../src/binding.cpp:154: error: 'sass_option_set_is_indented_syntax_src' was not declared in this scope
    remote: ../src/binding.cpp:155: error: 'sass_option_set_source_comments' was not declared in this scope
    remote: ../src/binding.cpp:156: error: 'sass_option_set_omit_source_map_url' was not declared in this scope
    remote: ../src/binding.cpp:157: error: 'sass_option_set_source_map_embed' was not declared in this scope
    remote: ../src/binding.cpp:158: error: 'sass_option_set_source_map_contents' was not declared in this scope
    remote: ../src/binding.cpp:159: error: 'sass_option_set_source_map_file' was not declared in this scope
    remote: ../src/binding.cpp:160: error: 'sass_option_set_include_path' was not declared in this scope
    remote: ../src/binding.cpp:161: error: 'sass_option_set_precision' was not declared in this scope
    remote: ../src/binding.cpp: At global scope:
    remote: ../src/binding.cpp:164: error: 'Sass_Context' has not been declared
    remote: ../src/binding.cpp: In function 'void GetStats(sass_context_wrapper*, int*)':
    remote: ../src/binding.cpp:167: error: 'sass_context_get_included_files' was not declared in this scope
    remote: ../src/binding.cpp:171: error: 'nullptr' was not declared in this scope
    remote: ../src/binding.cpp: At global scope:
    remote: ../src/binding.cpp:179: error: 'Sass_Context' has not been declared
    remote: ../src/binding.cpp: In function 'void GetSourceMap(sass_context_wrapper*, int*)':
    remote: ../src/binding.cpp:184: error: 'sass_context_get_error_status' was not declared in this scope
    remote: ../src/binding.cpp:188: error: 'sass_context_get_source_map_string' was not declared in this scope
    remote: ../src/binding.cpp: At global scope:
    remote: ../src/binding.cpp:198: error: 'Sass_Context' has not been declared
    remote: ../src/binding.cpp: In function 'int GetResult(sass_context_wrapper*, int*)':
    remote: ../src/binding.cpp:201: error: 'sass_context_get_error_status' was not declared in this scope
    remote: ../src/binding.cpp:204: error: 'sass_context_get_output_string' was not declared in this scope
    remote: ../src/binding.cpp: In function 'void make_callback(uv_work_t*)':
    remote: ../src/binding.cpp:221: error: 'sass_data_context_get_context' was not declared in this scope
    remote: ../src/binding.cpp:224: error: 'sass_file_context_get_context' was not declared in this scope
    remote: ../src/binding.cpp:227: error: cannot convert 'Sass_Context*' to 'int*' for argument '2' to 'int GetResult(sass_context_wrapper*, int*)'
    remote: ../src/binding.cpp:235: error: 'sass_context_get_error_json' was not declared in this scope
    remote: ../src/binding.cpp: In function 'v8::Handle<v8::Value> Render(const v8::Arguments&)':
    remote: ../src/binding.cpp:258: error: 'sass_make_data_context' was not declared in this scope
    remote: ../src/binding.cpp: In function 'v8::Handle<v8::Value> RenderSync(const v8::Arguments&)':
    remote: ../src/binding.cpp:275: error: 'sass_make_data_context' was not declared in this scope
    remote: ../src/binding.cpp:276: error: 'sass_data_context_get_context' was not declared in this scope
    remote: ../src/binding.cpp:283: error: cannot convert 'Sass_Context*' to 'int*' for argument '2' to 'int GetResult(sass_context_wrapper*, int*)'
    remote: ../src/binding.cpp:287: error: 'sass_context_get_error_json' was not declared in this scope
    remote: ../src/binding.cpp: In function 'v8::Handle<v8::Value> RenderFile(const v8::Arguments&)':
    remote: ../src/binding.cpp:304: error: 'sass_make_file_context' was not declared in this scope
    remote: ../src/binding.cpp: In function 'v8::Handle<v8::Value> RenderFileSync(const v8::Arguments&)':
    remote: ../src/binding.cpp:321: error: 'sass_make_file_context' was not declared in this scope
    remote: ../src/binding.cpp:322: error: 'sass_file_context_get_context' was not declared in this scope
    remote: ../src/binding.cpp:328: error: cannot convert 'Sass_Context*' to 'int*' for argument '2' to 'int GetResult(sass_context_wrapper*, int*)'
    remote: ../src/binding.cpp:332: error: 'sass_context_get_error_json' was not declared in this scope
    remote: make: *** [Release/obj.target/binding/src/binding.o] Error 1
    remote: make: Leaving directory '/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxxx/app-root/runtime/repo/node_modules/node-sass/build'
    remote: gyp ERR! build error 
    remote: gyp ERR! stack Error: 'make' failed with exit code: 2
    remote: gyp ERR! stack     at ChildProcess.onExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
    remote: gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
    remote: gyp ERR! System Linux 2.6.32-504.3.3.el6.x86_64
    remote: gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    remote: gyp ERR! cwd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxxx/app-root/runtime/repo/node_modules/node-sass
    remote: gyp ERR! node -v v0.10.25
    remote: gyp ERR! node-gyp -v v0.12.2
    remote: gyp ERR! not ok

**Comment by am11** [comment]
@aschmid that is not a tunneling issue which is described here and https://github.com/sass/node-sass/issues/604, but the issue you are reporting is due to the reason you have older gcc (libsass needs gcc 5+ to compile). Also we haven't released the next version yet after fixing the tunneling issue. 

Besides what command are you running to install node-sass? Normally it is `npm install node-sass`, which downloads the readymade binary and doesn't require gcc, Python and other tools to build node-sass on target system.

**Comment by aschmid** [comment]
@am11 i am just pushing the openshift repo with node-sass  in the package.json as a dependency without specifying a version. what i posted is the remotes log output.

**Comment by am11** [comment]
`npm install node-sass@2.0.0` is released!
Checkout the release notes: https://github.com/sass/node-sass/releases/tag/v2.0.0
