### ISSUE TITLE
Why does node-sass downloads\builds the binding on each npm install? 

### ISSUE THREAD

**Issue by yonidor** [sass/node-sass#654]
Hi,

I have a problem where we just integrated node-sass, on our CI machines, each build calls npm install which redownloads the binding file. I saw the option to suppress the download and let python build the binding for me, but my question is why can't the binding be downloaded as part of the package?

**Comment by am11** [comment]
Hi,

**Q. Why does node-sass downloads\builds the binding on each npm install?**

Preciseness & Bandwidth-friendliness:

Each platform (Mac, Linux etc.) has its own binary for each architecture (x86-64, x86-32), so instead of downloading everything on your system, this way we detect your system and download the matching binary from a separate repo: https://github.com/sass/node-sass-binaries.

**Q. Is this the best way?**

npm package is a distilled form, we cannot modify or make decisions at install time to cherry pick constituents of package. We used to bundle binaries in npm sometime ago. We realised this approach is better due to the aforementioned reason.

**Q. What is the other option?**

Download all binaries, and delete them except the one which is suitable for your system. This approach is non-bandwidth-friendly.

Related: https://github.com/sass/node-sass/issues/655.

**Comment by yonidor** [comment]
First of all, great answer.

The optimal solution i see for me is to have a local copy of binding.node (in the version i need) and copy it to the appropriate place right after 'npm install' is ran. 
Can i achieve that by using SKIP_SASS_BINARY_DOWNLOAD_FOR_CI and SKIP_NODE_SASS_TESTS?

**Comment by am11** [comment]
Implicitly yes. `SKIP_SASS_BINARY_DOWNLOAD_FOR_CI = true` will skip the download and try to manually build the binary. Then `SKIP_NODE_SASS_TESTS = true` will skip building the binary. You can then manually download the binary in `/vendor` directory.

**Comment by yonidor** [comment]
Cool, many thanks!

**Comment by janusch** [comment]
@am11 Hey,
this issue touches exactly my problem. I have put the binaries into the node-sass directory in vendor/. Now the postinstall fails because of node-gyp not being able to rebuild. How can I skip the node-gyp re-build and just use the binaries in vendor/ ?

**Comment by am11** [comment]
Hej @janusch,

Run:

```sh
# in CLI
node -p "[process.platform, '-', process.arch, '-', process.versions.modules].join('')"
```

and note its output. Iyou have a directory with that name under `vendor/`, then postinstall will skip rebuilding the binary.

**Comment by janusch** [comment]
@am11 thank you for getting back to me!

Here is the output from from the command above:

´´´
test_i$ node -p "[process.platform, '-', process.arch, '-', process.versions.modules].join('')"
linux-x64-46
```

I think I realized what went wrong, the vendor dir is not included when I `npm publish` . Do you know how I can add the binaries and publish to my local npm?

**Comment by janusch** [comment]
@am11 Hey,
I just tried to publish node-sass with binaies after `git clone`ing the node-sass repo and `git checkout` of the last stable release. Sadly it still does not include `vendor/` dir. I do not have experience with publishing node packages, so it is probably a stupid mistake. If you know what I am doing wrong, please let me know.

Would it make more sense to go for plan B and install a libsass linux package instead and node-sass can skip installing any binaries?

Thank you again for taking the time to walk me through this!

**Comment by xzyfer** [comment]
I believe this is fixed on master. We'll be releasing 3.5.0 stable in a
couple days. Just waiting on LibSass to finish up 3.3.5.

**Comment by janusch** [comment]
@xzyfer sorry. I used this issue for my own problem with not being able to download binaries due to no internet connection. I think i just figured it out. Just had to add the `vendor` dir with the binaries downloeaded for my system into `package.json`s `files` array 

```json
"files": [
    "bin",
    "binding.gyp",
    "lib",
    "scripts",
    "vendor",
    "src"
  ]
```

Sorry again for putting this into an issue that was meant for something else, I had lost track.
Keep up the great work!

**Comment by janusch** [comment]
Hey @am11 @xzyfer ,
Sorry to bother you again. I thought I had figured it out. But now on testing without internet. I still get errors in the postinstall process.

I had to pull in the libsass git submodule. Now it builds but I am not sure what should go into the patched node-sass package that is fully standalone. 

Could you point me to a guide that helps with builiding a standalone node-sass package. 
E.g. do I need to set those env. variables? SASS_BINARY_PATH	 and LIBSASS_EXT. I am currently setting `SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true` that helped a bit when there is not connection.

Could you please give me an example of the SASS_BINARY_PATH for when the binaries are within the node_modules/node-sass/vendor dir?

How can building libsass be skipped, or do I need to add the git submodule to the package?

Would be delighted if we get this to work!

**Comment by am11** [comment]
Are you trying to install node-sass offline with git source? If so, you would need to have the repo cloned recursively to pull the libsass submodule: `git clone https://github.com/sass/node-sass --recursive`; unfortunately, github's zip does not include the submodules. Alternatively, you can download libsass zip in addition to node-sass, extract node-sass in `./node-sass`, extract libsass in `./node-sass/src/libsass` and run: `cd ./node-sass && npm install`.

**Comment by janusch** [comment]
@am11 great, this fixed it!
Thank you very much for pointing this out. 
Finally I have a working package of node-sass with binaries, thank you!
