### ISSUE TITLE
Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 209.

### ISSUE THREAD

**Issue by weichx** [sass/node-sass#713]
I am randomly seeing this error when using the importer function. My intention is to treat @import like require(). Here is the offending code: 

```javascript
importer: function (url, prev, done) {
               if(imported[url]) {
                    done({contents: ''});
                } else {
                    imported[url] = true;
                    done({file: url});
                }
            }
````

**Comment by am11** [comment]
Yes and I get it with io.js on TravisCI intermittently. There is a race condition in our binding code. On a bright side it works (mostly) and the vNext or vNext->Next will fix this issue. Actually this is already fixed in this work-in-progress PR: #644.

**Comment by weichsem** [comment]
I'll hang tight until that merges then, thanks.

**Comment by am11** [comment]
Status: v3.0.0-pre is out but this issue persists, since #644 isn't merged. Meanwhile try out the new API.

**Comment by haf** [comment]
I'm starting to become a regular in this repository, unwillingly! https://github.com/webpack/webpack/issues/904 - related perhaps?

**Comment by jedwards1211** [comment]
Yes, it's related.  I had to downgrade to sass-loader 0.5.0 and node-sass 2.0.1, then the error went away.  I didn't have any luck with node-sass 3.0.0-alpha.0 either.

Thank you guys for tipping me off to this, I don't think I would have had a clue otherwise!

**Comment by jcreamer898** [comment]
Currently seeing this issue still in .beta4.

**Comment by wubenhe** [comment]
+1 I have to downgrade my sass-loader to 0.3.0. 
So that I can use Material UI for react.

**Comment by jcreamer898** [comment]
@wubenhe, you might actually be able to use `0.4.2` of the `sass-loader` that one worked for me. If you run `npm info sass-loader` you can see all the available versions. They're not all listed on the github site's tag list.

**Comment by ShMcK** [comment]
@jcreamer898 Thanks! `0.4.2` worked for me!

**Comment by xiaobuu** [comment]
+1 Have to downgrade the sass-loader now

**Comment by wubenhe** [comment]
@jcreamer898 Thanks! 0.4.2 worked for me as well.

**Comment by jhnns** [comment]
For all those using the sass-loader:

I've managed to write a version of sass-loader that provides the same features while depending on node-sass `2.1.1`. It's on a [separate branch](https://github.com/jtangelder/sass-loader/tree/release/v0.6.0) and can be installed via `npm i sass-loader@0.6.x`. Please note, that sass-loader `0.6.0` is listing node-sass as `peerDependency` as well.

**Comment by xiaobuu** [comment]
@jhnns Thank you! But I tried the sass-loader 0.6.0 and the same assertion failed error occurred. 0.4.2 works for me.

**Comment by am11** [comment]
@jhnns, this is true it happens when using Custom Importers and Custom Functions. 
IMO, this is due to one of the two reasons:

* uv tries to close loop when the resource is still busy: https://github.com/sass/node-sass/issues/794 is one symptom. Given our setup, it is hard to spot the exact cause of random hang-ups and different versions of v8 (`node -p process.versions.v8 && node -p process.versions.modules`) present different behaviour in this regard.
* Our GC de-allocates vector-of-pointers incorrectly (@matryo, even `ctx_w->importers.emtpy()` check does not help in such cases). 
  * We were doing it wrong by iterating over vector and modifying its state in body. 
  * I have changed the behavior using vector of C++11's  "smart pointers". 
    * I think it will fix most of the issues, but I can still see assertion aborts with MSVCR when compiled with debug configuration (`node scripts/build -f -d`). 
    * However, with release configuration it works fine.
  * I have planned few minor fixes after beta5, but can't figure out how to fix those vector related assertion failures for good.

Having said that, beta5 is much more stable as far as this issue is concerned. Please keep posting your experiences.

Note: v3.0.0-beta.5 will be published today shortly afterwards.

**Comment by vegetableman** [comment]
Thanks @jcreamer898 for the downgrade suggestion. working version: ```node-sass: 2.0.1 && sass-loader: 0.4.2```

**Comment by xiaobuu** [comment]
node-sass: 2.1.1 works as well

**Comment by sarenji** [comment]
With `beta.5` (and `.4`), I get either segfaults or these two errors:
```bash
Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 171.
[1]    38326 abort      gulp scss
# or
Assertion failed: (0), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 199.
[1]    38386 abort      gulp scss
```
Notably, these cease to be a problem the moment I tell `gulp-sass` to use `node-sass`'s `renderSync` rather than `render`.

**Comment by jhnns** [comment]
`renderSync` doesn't use libuv's loop afaik, so yeah, using sync compilation probably solves the problem...

**Comment by quicksnap** [comment]
Also a `sass-loader` user, tried using 0.6, but still had intermittent failures (~50%). 0.4.2 is working well so far!

**Comment by xzyfer** [comment]
@am11 I've recently bumped into this in beta5 with https://github.com/at-import/node-sass-import-once

**Comment by akloeber** [comment]
For those still looking for a workaround: `sass-loader@0.6.0` does not work neither as it depends on  `node-sass@2.1.1` which, according to the comments in https://github.com/sass/node-sass/issues/713, is also one of the versions that provoke these errors.

The latest working version seems to be `node-sass@2.0.1` but even explicitely depending on `node-sass@2.0.1` as a peer dependency is not a workaround because it does not satisfy `^2.1.1`.

**Comment by chriseppstein** [comment]
This error is making node-sass basically unusable for me.

**Comment by am11** [comment]
For the people who are seeing this issue in 2.1.1 and not in 2.0.1; both have ditto binaries. I didn't even recompile them! The only diff between two version is that I moved nan from devDependencies to dependencies. The other *advantage* of having 2.1.1 over 2.0.1 is that 2.1.1 covers most versions of io.js. So either people are hallucinating or they haven't yet encountered the bug with 2.0.1 yet.

**Comment by am11** [comment]
@xzyfer, I am unable to reproduce this issue on Windows after running tests suite back to back 10 times with [this diff](https://gist.github.com/am11/e1304a023c695c810bdc). Normally it chokes in first 3 attempts. It might be a luck thing or it might be a fix. :)

For the record, I reproduce it locally by running node-sass test suite over and over on Linux and Windows. It normally aborts the test runner with Assertion failure in first four attempts. As far as I can tell, there are no known tangible repro steps for this issue, against which we can debug it properly.

**Comment by xzyfer** [comment]
I can this against the failing code base on Monday and let you know if it helps.

**Comment by akloeber** [comment]
@am11: I can confirm that. I forked `sass-loader` and changed the dependency to `node-sass@2.0.1` but ran into the same error afterwards.

**Comment by saper** [comment]
Everyone: please see if #854 fixes this problem.

**Comment by xzyfer** [comment]
@saper #854 appears to fix this exception for me.

**Comment by xzyfer** [comment]
Looks like this is causing CI to randomly fail now

**Comment by saper** [comment]
@xzyfer do you mean the #854 is causing CI to fail or the original problem? `Assertion failed: (handle->flags & UV_CLOSING)` is known to fail our CI for quite a some time :(

**Comment by xzyfer** [comment]
The latter. I hadn't previously noticed the CI failures.

**Comment by saper** [comment]
Ah, yes. But #854 should fix it I hope.

**Comment by xzyfer** [comment]
It has in my experience

**Comment by henriquea** [comment]
Same here `node-sass@2.1.1` did work with `sass-loader@0.4.2` but not with `sass-loader@0.6.0`.

**Comment by saper** [comment]
`sass-loader@0.6.0` does not seem to accept `node-sass` betas, but you can try taking https://github.com/sass/node-sass/pull/854 from git and see if it helps.Should be compatible with node-sass 3.0.

**Comment by henriquea** [comment]
Thanks @saper! I'll give it a try later.

**Comment by saper** [comment]
What's interesting, I also noticed this bug on node-sass 2.1.1

**Comment by chriseppstein** [comment]
This was affecting me about 80% of the time. I pulled the latest and built it and it seems to work great now. No crashes after 40 trial builds. Thank you :heart_eyes:!

**Comment by mingfang** [comment]
This is still happening for me

**Comment by saper** [comment]
@mingfang which git commit are you at? (Just check with `git show HEAD`).
Are you using some other module that has `node-sass` embedded into its own dependencies?

**Comment by xzyfer** [comment]
@mingfang this fix is not in a stable release yet. Please be patient.

**Comment by mingfang** [comment]
Thanks for the effort on this.  
I've downgraded to a working combinations of node-sass 2.1.1 and sass-loader 0.4.2.

**Comment by saper** [comment]
2.1.1 has this bug also but it occurs not so often

**Comment by xzyfer** [comment]
This has been resolved in 3.0.0-beta.7.

```
npm install node-sass@beta
```

**Comment by jhnns** [comment]
Awesome :+1:

**Comment by krsmedlund** [comment]
Earlier versions.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ webpack -c --progress --debug
 55% 231/305 build modules{ file: './_config.scss' }
 65% 302/326 build modules{ file: './_mixins.scss' }
 69% 461/463 build modules{ file: './_config.scss' }
 69% 462/463 build modules{ file: './_mixins.scss' }
Hash: dc1f3d29e0ec30a98d43
Version: webpack 1.8.10
Time: 12752ms
        Asset     Size  Chunks             Chunk Names
   js/main.js   4.7 MB       0  [emitted]  main
css/style.css  1.87 kB       0  [emitted]  main
   [0] multi main 52 bytes {0} [built]
    + 460 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

Current version
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ webpack -c --progress --debug
 55% 230/306 build modules{ file: './_config.scss' }
{ file: './_config.scss' }
 62% 267/308 build modulesnode: ../deps/uv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.
Aborted (core dumped)
```

git master branch
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ webpack -c --progress --debug
 69% 458/461 build modulesvagrant@vagrant-ubuntu-trusty-64:/vagrant$
```

So with latest master of today it doesnt cure dump just exits silently with no errors and no output, still doesnt produce any files.

**Comment by saper** [comment]
@krsmedlund How can I reproduce this (no clue about webpack)

**Comment by iroy2000** [comment]
Nice that I see this, I was using "sass-loader": "^0.6.0", and it sometimes work and sometimes not, and very inconsistent.  But after bump down the version to "sass-loader": "^0.4.2",, it looks good now.  Thanks.

**Comment by xzyfer** [comment]
This is a known issue in older version of node-sass which sass-loader is using. Unfortunately sass-loader doesn't currently support the stable ^3 release. This needs to be fixed on their end /cc @jhnns

**Comment by jhnns** [comment]
I've just released `v1.0.2` which uses `node-sass@3.1.1`

**Comment by henriquea** [comment]
Nice one! Thanks @jhnns :)

**Comment by heliosbryan** [comment]
Downgrading sass-loader to 0.4.2 worked for me, thanks!
